global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warnings'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#flowcast-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ .CommonAnnotations.grafana_url }}'
          - type: button
            text: 'View in Prometheus'
            url: '{{ .CommonAnnotations.prometheus_url }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#flowcast-critical'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ .CommonAnnotations.grafana_url }}'
          - type: button
            text: 'View in Prometheus'
            url: '{{ .CommonAnnotations.prometheus_url }}'

  - name: 'slack-warnings'
    slack_configs:
      - channel: '#flowcast-warnings'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View in Grafana'
            url: '{{ .CommonAnnotations.grafana_url }}'
          - type: button
            text: 'View in Prometheus'
            url: '{{ .CommonAnnotations.prometheus_url }}'

templates:
  - '/etc/alertmanager/template/*.tmpl' 